name: trade_to_ohlc
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: trade_events
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: ohlc_events
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
